const express = require("express");
const errorHandler = require("../middlewares/errorHandler");
const authentication = require("../middlewares/authentication");
const Controller = require("../controllers/controller");
const router = express.Router();
router.use("/", require("./userRouter"));
router.use(authentication);
router.get("/user", Controller.getProfile);
router.put("/update", Controller.updateProfile);
router.use("/interview", require("./interviewRouter"));
router.use(errorHandler);
module.exports = router;
